version: "3.8"
services:
  cvwo-front:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV='production'
    ports:
      - "8080:80"

    stdin_open: true
    tty: true
