version: "3.8"
services:
  cvwo-front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    stdin_open: true
    tty: true
